services:
  backend:
    build:
      context: ./app-backend
    container_name: weather-backend
    ports:
      - "5001:5000"
    env_file:
      - ./app-backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weatherdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
