version: "3.8"

services:
  backend:
    build:
      context: ./app-backend
    container_name: weather-backend
    ports:
      - "5001:5000"
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weatherdb
      BG_REMOVAL_URL: http://bg-removal:8000/remove-bg
    env_file:
      - ./app-backend/.env
    depends_on:
      - db
      - bg-removal
    volumes:
      - ./app-backend:/app
      - /app/node_modules
      - ./app-backend/uploads:/app/uploads
      - ./app-backend/prisma:/app/prisma

  frontend:
    build:
      context: ./app-mobile/my-app
    container_name: weather-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app-mobile/my-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weatherdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bg-removal:
    build:
      context: ./bg-removal-service
    ports:
      - "8000:8000"


volumes:
  pgdata:
