name: CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-backend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: "file:./dev.db"

      - name: Reset DB (SQLite)
        run: npx prisma migrate reset --force --skip-generate --skip-seed
        env:
          DATABASE_URL: "file:./dev.db"

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: "file:./dev.db"

      - name: Test Docker build
        run: docker build -t weather-backend .
