name: example

on:
  push:
    branches: [documentation]

jobs:
  ex-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: print hello
        run: echo "===========hello ================="
        